config/routes.rb
Rails.application.routes.draw do
  resources :members, :only => [:index, :new, :create, :show]
  resources :examples
  get 'user/new'
  get 'user/create'
  devise_for :auths
  get 'dashboard/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'dashboard#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/auth.rb
# == Schema Information
#
# Table name: auths
#
#  id                     :uuid             not null, primary key
#  auth_able_type         :string           not null
#  current_sign_in_at     :datetime
#  current_sign_in_ip     :string
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  last_sign_in_at        :datetime
#  last_sign_in_ip        :string
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  role                   :string           default("user"), not null
#  sign_in_count          :integer          default(0), not null
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  auth_able_id           :uuid             not null
#
# Indexes
#
#  index_auths_on_auth_able_id          (auth_able_id)
#  index_auths_on_auth_able_type        (auth_able_type)
#  index_auths_on_email                 (email) UNIQUE
#  index_auths_on_reset_password_token  (reset_password_token) UNIQUE
#
class Auth < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :trackable,
         :recoverable, :rememberable, :validatable

  belongs_to :auth_able, polymorphic: true, optional: true
end

app/models/builder/model.rb
class Builder::Model < Hashie::Mash
  def initialize(params)
    params.each_pair do |k, v|
      self[k] = v
    end
    @attributes = params
  end

  def attributes
    ActiveSupport::HashWithIndifferentAccess.new(@attributes).symbolize_keys
  end
end

app/models/example.rb
# == Schema Information
#
# Table name: examples
#
#  id         :bigint           not null, primary key
#  title      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Example < ApplicationRecord
end

app/models/member.rb
# == Schema Information
#
# Table name: members
#
#  id           :uuid             not null, primary key
#  is_active    :boolean
#  settings     :jsonb
#  subscription :date
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  user_id      :uuid             not null
#
class Member < ApplicationRecord
  belongs_to :user
  has_one :auth, as: :auth_able, dependent: :destroy, class_name: 'Auth'
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id           :uuid             not null, primary key
#  address      :text
#  email        :string           default(""), not null
#  full_name    :string
#  phone_number :string
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#
# Indexes
#
#  index_users_on_email         (email) UNIQUE
#  index_users_on_phone_number  (phone_number) UNIQUE
#
class User < ApplicationRecord
  has_one :auth, as: :auth_able, dependent: :destroy, class_name: 'Auth'
  has_many :members

  enum role: {
    super_admin: 'super_admin',
    admin:       'admin',
    user:        'user',
    trial:       'trial'
  }

  def self.allowed_role
    roles.keys
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_auth!

  protected

  def after_sign_in_path_for(resource)
    # return the path based on resource
    '/dashboard/index'
  end

  def after_sign_out_path_for(scope)
    # return the path based on scope
    '/auths/sign_in'
  end

  def after_sign_up_path_for(resource)
    # return the path based on resource
    '/dashboard/index'
  end

  def response_success(object)
    object
  end

  def response_failure!(object, message, flash_type: :notice)
    if message.class == String
      flash[flash_type] = message
    else
      flash[flash_type] = message.as_json['active_model_errors']
    end
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_auth!
  def index
  end
end

app/controllers/examples_controller.rb
class ExamplesController < ApplicationController
  before_action :set_example, only: %i[show edit update destroy]

  # GET /examples or /examples.json
  def index
    @examples = Example.all
  end

  # GET /examples/1 or /examples/1.json
  def show
  end

  # GET /examples/new
  def new
    @example = Example.new
  end

  # GET /examples/1/edit
  def edit
  end

  # POST /examples or /examples.json
  def create
    @example = Example.new(example_params)

    respond_to do |format|
      if @example.save
        format.html { redirect_to example_url(@example), notice: 'Example was successfully created.' }
        format.json { render :show, status: :created, location: @example }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @example.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /examples/1 or /examples/1.json
  def update
    respond_to do |format|
      if @example.update(example_params)
        format.html { redirect_to example_url(@example), notice: 'Example was successfully updated.' }
        format.json { render :show, status: :ok, location: @example }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @example.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /examples/1 or /examples/1.json
  def destroy
    @example.destroy

    respond_to do |format|
      format.html { redirect_to examples_url, notice: 'Example was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_example
    @example = Example.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def example_params
    params.require(:example).permit(:title)
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  def index
    # build params
    params.permit!
    params[:user_id] = current_auth.auth_able_id
    params[:limit] = params[:limit].present? ? params[:limit] : 10
    params[:offset] = params[:offset].present? ? params[:offset] : 1

    # to interactor
    interactor = Core::UseCases::Members::UserGetMembers
    parameters = interactor.parameters(params.to_hash)
    result     = interactor.new(parameters).result

    # build response
    @response = Dry::Matcher::ResultMatcher.call(result) do |matcher|
      yield matcher if block_given?
      matcher.success { |response| response_success({ members: response[:response], pagination: response[:pagination] }) }
      matcher.failure { |errors| { status: errors || :error } }
    end
  end

  def new
    @member = Member.new
  end

  def create
    parameters = member_params
    parameters[:user_id] = current_auth.auth_able_id
    parameters[:is_active] = true
    parameters[:subscription] = build_subscription member_params[:subscription]

    # to interactor
    interactor = Core::UseCases::Members::UserCreateNewMember
    parameters = interactor.parameters(parameters.to_hash)
    result     = interactor.new(parameters).result

    # build response
    @response = Dry::Matcher::ResultMatcher.call(result) do |matcher|
      yield matcher if block_given?
      matcher.success do |response|
        redirect_to action: 'show', id: response.id
      end
      matcher.failure do |errors|
        redirect_to members_path, alert: errors.to_s
      end
    end
  end

  def show
    params.permit!
  end

  private

  # Only allow a list of trusted parameters through.
  def member_params
    params.require(:member).permit(:email, :password, :subscription)
  end

  def build_subscription params
    case params
    when 'trial'
      Time.now + 1.day
    when 'one_month'
      Time.now + 30.day
    when 'one_year'
      Time.now + 365.day
    else
      Time.now + 1.day
    end
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def new
  end

  def create
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/examples_helper.rb
module ExamplesHelper
end

app/views/dashboard/index.html.erb
<div>
  <h1 class="font-bold text-4xl">Dashboard#index</h1>
  <p>Find me in app/views/dashboard/index.html.erb</p>
</div>

app/views/examples/_example.html.erb
<div id="<%= dom_id example %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Title:</strong>
    <%= example.title %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this example", example, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this example', edit_example_path(example), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/examples/_form.html.erb
<%= form_with(model: example, class: "contents") do |form| %>
  <% if example.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(example.errors.count, "error") %> prohibited this example from being saved:</h2>

      <ul>
        <% example.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :title %>
    <%= form.text_field :title, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/examples/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing example</h1>

  <%= render "form", example: @example %>

  <%= link_to "Show this example", @example, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to examples", examples_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/examples/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Examples</h1>
    <%= link_to 'New example', new_example_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="examples" class="min-w-full">
    <%= render @examples %>
  </div>
</div>

app/views/examples/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New example</h1>

  <%= render "form", example: @example %>

  <%= link_to 'Back to examples', examples_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/examples/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @example %>

    <%= link_to 'Edit this example', edit_example_path(@example), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this example', example_path(@example), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to examples', examples_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BoilerplateInit</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>
<body>
<div class="w-full flex flex-wrap">
  <div class="drawer">
    <input id="my-drawer" type="checkbox" class="drawer-toggle"/>
    <div class="drawer-content mx-4">
      <!-- Page content here -->
      <div class="navbar bg-base-100 shadow-md">
        <div class="flex-none">
          <label for="my-drawer" class="btn btn-ghost drawer-button">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" class="inline-block w-5 h-5 stroke-current">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16"></path>
            </svg>
          </label>
        </div>
        <div class="flex-1">
          <a class="btn btn-ghost normal-case text-xl">WAB Enterprise</a>
        </div>
      </div>
      <div class="mx-8 mt-4">
        <%= yield %>
      </div>
    </div>
    <div class="drawer-side">
      <label for="my-drawer" class="drawer-overlay"></label>
      <ul class="menu p-4 overflow-y-auto w-60 bg-base-100 text-base-content">
        <!-- Sidebar content here -->
        <p class="mb-4">WAB Enterprise</p>
        <li><a>Sidebar Item 1</a></li>
        <li><a>Sidebar Item 2</a></li>
        <%= button_to 'Logout', destroy_auth_session_path, method: :delete, class: "btn btn-sm mt-16 mx-auto" %>
      </ul>
    </div>
  </div>
</div>
</div>
</body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BoilerplateInit</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
  <style>
      @import url('https://fonts.googleapis.com/css?family=Karla:400,700&display=swap');

      .font-family-karla {
          font-family: karla;
      }
  </style>
</head>
<body class="bg-white font-family-karla h-screen">

<div class="w-full flex flex-wrap">

  <!-- Login Section -->
  <div class="w-full md:w-1/2 flex flex-col">
    <div class="flex flex-col justify-center md:justify-start my-auto pt-8 md:pt-0 px-8 md:px-24 lg:px-32">
      <p class="text-center text-3xl text-black">Welcome.</p>
      <% if notice %>
        <div class="alert alert-info shadow-lg">
          <div>
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" class="stroke-current flex-shrink-0 w-6 h-6">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"></path>
            </svg>
            <span><%= notice %></span>
          </div>
        </div>
      <% end %>
      <% if alert %>
        <div class="alert alert-error shadow-lg">
          <div>
            <svg xmlns="http://www.w3.org/2000/svg" class="stroke-current flex-shrink-0 h-6 w-6" fill="none" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 14l2-2m0 0l2-2m-2 2l-2-2m2 2l2 2m7-2a9 9 0 11-18 0 9 9 0 0118 0z"/>
            </svg>
            <span><%= alert %></span>
          </div>
        </div>
      <% end %>
      <!--      <form class="flex flex-col pt-3 md:pt-8" onsubmit="event.preventDefault();">-->
      <!--        <div class="flex flex-col pt-4">-->
      <!--          <label for="email" class="text-lg">Email</label>-->
      <!--          <input type="email" id="email" placeholder="your@email.com" class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 mt-1 leading-tight focus:outline-none focus:shadow-outline">-->
      <!--        </div>-->

      <!--        <div class="flex flex-col pt-4">-->
      <!--          <label for="password" class="text-lg">Password</label>-->
      <!--          <input type="password" id="password" placeholder="Password" class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 mt-1 leading-tight focus:outline-none focus:shadow-outline">-->
      <!--        </div>-->

      <!--        <input type="submit" value="Log In" class="bg-black text-white font-bold text-lg hover:bg-gray-700 p-2 mt-8">-->
      <!--      </form>-->
      <%= yield %>
      <!--      <div class="text-center pt-12 pb-12">-->
      <!--        <p>Don't have an account? <a href="register.html" class="underline font-semibold">Register here.</a></p>-->
      <!--      </div>-->
    </div>

  </div>

  <!-- Image Section -->
  <div class="w-1/2 shadow-2xl">
    <img class="object-cover w-full h-screen hidden md:block" src="https://source.unsplash.com/IXUM4cJynP0">
  </div>
</div>

</body>
</html>

app/views/layouts/includes/_flash_message.html.erb
<% if flash.any? %>
  <% flash.each do |type, msg| %>
    <% if type.eql?('alert') %>
      <div class="alert alert-error shadow-lg w-1/2 mx-auto">
        <div>
          <svg xmlns="http://www.w3.org/2000/svg" class="stroke-current flex-shrink-0 h-6 w-6" fill="none" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 14l2-2m0 0l2-2m-2 2l-2-2m2 2l2 2m7-2a9 9 0 11-18 0 9 9 0 0118 0z"/>
          </svg>
          <span><%= msg %></span>
        </div>
      </div>
    <% end %>

    <% if type.eql?('notice') %>
      <div class="alert alert-success shadow-lg w-1/2 mx-auto">
        <div>
          <svg xmlns="http://www.w3.org/2000/svg" class="stroke-current flex-shrink-0 h-6 w-6" fill="none" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"/>
          </svg>
          <span><%= notice %></span>
        </div>
      </div>
    <% end %>
  <% end %>
<% end %>

app/views/layouts/main.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BoilerplateInit</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>

<body>
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>
<%= yield %>
<h1 class="text-3xl font-bold underline">
    Hello world!
</h1>

</body>
</html>

app/views/member/index.html.erb
<div>
  <h1 class="font-bold text-2xl">Dashboard</h1>
  <div class="flex justify-between">
    <div class="text-sm breadcrumbs">
      <ul>
        <li><a>Dashboard</a></li>
        <li>List Members</li>
      </ul>
    </div>
    <button class="btn btn-sm">Add New Member</button>
  </div>
</div>
<% if @response[:members].present? %>
  <div class="overflow-x-auto mt-6">
    <table class="table w-full">
      <!-- head -->
      <thead>
      <tr>
        <th>#</th>
        <th>Email</th>
        <th>Role</th>
        <th>Subscription</th>
        <th>Action</th>
      </tr>
      </thead>
      <tbody>
      <% @response[:members].each_with_index do |member, index| %>
        <tr class="hover">
          <th><%= index + 1 %></th>
          <td><%= member.email %></td>
          <td><%= member.role %></td>
          <td><%= member.subscription %></td>
          <td><a class="btn btn-sm">Action</a></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
<% else %>
  <div class="mt-8">
    <div class="card w-96 bg-base-200 mx-auto">
      <div class="card-body items-center text-center ">
        <h2 class="card-title">Data Not Found!</h2>
        <p>You can add member to get members data</p>
        <div class="card-actions justify-end">
          <button class="btn btn-sm">Add New Member</button>
          <button class="btn btn-sm btn-ghost">Logout</button>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/members/_form.html.erb
<%= form_with(model: member, class: "w-1/2 mx-auto") do |form| %>
  <div class="my-5">
    <%= form.label :email %>
    <%= form.text_field :email, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :password %>
    <%= form.password_field :password, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :subscription %>
    <%= form.select :subscription, [['One Month', :one_month], ['One Year', :one_year]], { include_blank: "Choose Package" }, { class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" } %>
    <%#= form.text_field :title, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "btn btn-sm" %>
  </div>
<% end %>

app/views/members/index.html.erb
<div>
  <h1 class="font-bold text-2xl">Dashboard</h1>
  <div class="flex justify-between">
    <%= render 'breadcrumbs_member' %>
    <%= link_to 'Add New Member', new_member_path, class: "btn btn-sm" %>
  </div>
</div>
<% if @response[:members].present? %>
  <%= render 'layouts/includes/flash_message' %>
  <div class="overflow-x-auto mt-6">
    <table class="table w-full">
      <!-- head -->
      <thead>
      <tr>
        <th>#</th>
        <th>Email</th>
        <th>Role</th>
        <th>Status</th>
        <th>Subscription</th>
        <th>Action</th>
      </tr>
      </thead>
      <tbody>
      <% @response[:members].each_with_index do |member, index| %>
        <tr class="hover">
          <th><%= index + 1 %></th>
          <td><%= member.email %></td>
          <td><%= member.role %></td>
          <td><%= member.is_active %></td>
          <td><%= member.subscription %></td>
          <td><a class="btn btn-sm">Action</a></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
<% else %>
  <div class="mt-8">
    <div class="card w-96 bg-base-200 mx-auto">
      <div class="card-body items-center text-center ">
        <h2 class="card-title">Data Not Found!</h2>
        <p>You can add member to get members data</p>
        <div class="card-actions justify-end">
          <button class="btn btn-sm">Add New Member</button>
          <button class="btn btn-sm btn-ghost">Logout</button>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/user/create.html.erb
<div>
  <h1 class="font-bold text-4xl">User#create</h1>
  <p>Find me in app/views/user/create.html.erb</p>
</div>

app/views/user/new.html.erb
<div>
  <h1 class="font-bold text-4xl">User#new</h1>
  <p>Find me in app/views/user/new.html.erb</p>
</div>